### ISSUE TITLE
Listen for `Swap` and `Cancel` on-chain events to keep store clean

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-indexer-node#8]

**Comment by gpxl-dev** [comment]
FYI I encountered some issues with swap listeners when using ethers & infura http. Dug up this (closed) issue on the topic but AFAICT it's not actually resolved, and you may miss some events.

https://github.com/ethers-io/ethers.js/issues/1814

It's not a deal breaker - you will receive majority of events.
